update .dotfiles

diff --git a/bash/scripts/wgup b/bash/scripts/wgup
--- a/bash/scripts/wgup
+++ b/bash/scripts/wgup
@@ -1,9 +1,10 @@
 #!/bin/bash
 alacritty -e bash -c '\
-    wg-quick up wg0 || (wg-quick down wg0 && wg-quick up wg0);\
+    wg-quick up wg0 || (wg-quick down wg0 && wg-quick up wg0) || (echo "ERROR" && sleep infinity);\
     ping -c1 -q google.com;\
     while [ $? -ne 0 ]; do\
         wg-quick down wg0;\
         wg-quick up wg0;\
         ping -c1 -q google.com;\
-    done'
+    done && notify-send "VPN started!"
+    || (ping -c1 -q google.com || echo "ERROR" && sleep infinity;)'
